/**
 * Playwright webServer launcher for the admin e2e project.
 *
 * Boots the REAL admin/server.mjs with:
 *  - a generated ADMIN_TOKEN (exported as E2E_ADMIN_TOKEN for the specs)
 *  - ADMIN_DATA_DIR / ADMIN_UPLOAD_DIR pointed at a throwaway dir under qa-runs/
 *    so the developer's real CMS data is never touched by tests.
 *
 * Requires admin/server.mjs to honour ADMIN_DATA_DIR / ADMIN_UPLOAD_DIR env
 * overrides (small, backwards-compatible patch — defaults preserved).
 */
/* eslint-disable @typescript-eslint/no-require-imports -- plain CJS launcher, not bundled */
const { spawn } = require("node:child_process");
const path = require("node:path");
const fs = require("node:fs");

const PORT = process.env.E2E_ADMIN_PORT || 4271;
// Token is generated by playwright.config.ts (runner process) and passed via
// env so the workers' specs can read the same secret.
const TOKEN = process.env.E2E_ADMIN_TOKEN;
if (!TOKEN) {
  console.error("[admin-e2e] E2E_ADMIN_TOKEN missing — run via Playwright, not directly");
  process.exit(1);
}
const QA_DIR = path.resolve(__dirname, "..", "..", "qa-runs", "admin-e2e");
const DATA_DIR = path.join(QA_DIR, "data");
const UPLOAD_DIR = path.join(QA_DIR, "uploads");

// Seed the throwaway data dir using the SAME shape as admin/seed.mjs (the
// server auto-seeds itself when the data dir is empty, so we can also simply
// let it seed — but seeding here keeps the counts deterministic for asserts).
fs.mkdirSync(DATA_DIR, { recursive: true });
fs.mkdirSync(UPLOAD_DIR, { recursive: true });
const seed = require("../../admin/seed-data.cjs");

for (const [name, data] of Object.entries(seed)) {
  fs.writeFileSync(path.join(DATA_DIR, `${name}.json`), JSON.stringify(data, null, 2));
}

const child = spawn(process.execPath, ["server.mjs"], {
  cwd: path.resolve(__dirname, "..", "..", "admin"),
  env: {
    ...process.env,
    PORT: String(PORT),
    ADMIN_TOKEN: TOKEN,
    ADMIN_DATA_DIR: DATA_DIR,
    ADMIN_UPLOAD_DIR: UPLOAD_DIR,
  },
  stdio: "ignore",
});

// Expose the token to the Playwright worker processes (belt & braces — the
// config already set it in the runner env).
process.env.E2E_ADMIN_TOKEN = TOKEN;
console.log(`[admin-e2e] server on :${PORT} token=${TOKEN.slice(0, 6)}… data=${DATA_DIR}`);

function shutdown() {
  child.kill();
}
process.on("exit", shutdown);
process.on("SIGINT", () => process.exit(0));
process.on("SIGTERM", () => process.exit(0));

// Keep the event loop alive while the child runs.
child.on("exit", (code) => {
  console.error(`[admin-e2e] server exited early (code ${code})`);
  process.exit(1);
});
